### PR TITLE
Keep page and default layouts in sync, move assets to subdir

### PR DESCRIPTION
**Pull request by errordeveloper**
Seems like layouts where obviously out of sync.
Moving assets makes it remote_theme-friendly :)

### CODE REVIEW

**Comment by errordeveloper** [comment]
ping! :)

**Comment by adueck** [comment]
Thanks for your help!

**Comment by adueck** [comment]
Thanks for you help but this isn't quite ready to merge. (I merged it but now I've reverted it). Looks like when I build it now the javascript for the sharing bar is broken
```
[2018-06-08 01:31:02] ERROR `/scripts/rrssb.min.js' not found.
```

Sorry I'm really busy now, can you fix this in and put in the pull request again?

**Comment by errordeveloper** [comment]
Sorry, didn't realise it broke... I ended up using a different layout.

**Pull request merged**
